refactor: refactor code with the coding standard of Golang (#6)
* style: change resources files

* style: modify .gitignore

* style: change resources files

* feat: modify GitHub Actions configs

* docs: add GitHub Actions badge to README.md

* feat: modify GitHub Actions configs

* docs: add dev CI badge to README.md

Co-authored-by: JyCyunMe <JyCyun@JyCyun.me>

diff --git a/.github/workflows/github_build_release_windows.yml b/.github/workflows/github_build_release_windows.yml
--- a/.github/workflows/github_build_release_windows.yml
+++ b/.github/workflows/github_build_release_windows.yml
@@ -59,16 +59,61 @@ jobs:
           echo "BUILD_PATH=$BUILD_PATH" >> $env:GITHUB_ENV
           $BUILD_VERSION=cat .\versioninfo.json | jq -r '.StringFileInfo.ProductVersion'
           echo "BUILD_VERSION=$BUILD_VERSION" >> $env:GITHUB_ENV
-          echo "Build Version: $BUILD_VERSION"
-          $GIT_TAG="$BUILD_VERSION$(${env:GIT_BRANCH} -ne 'release' ? '-pre' : '')"
+          echo "Build Version: v$BUILD_VERSION"
+          $GIT_TAG="v$BUILD_VERSION$(${env:GIT_BRANCH} -ne 'release' ? '-pre' : '')"
           echo "GIT_TAG=$GIT_TAG" >> $env:GITHUB_ENV
           echo "Current Tag: $GIT_TAG"
 
-      #      # 构建前检查
-      #      - name: Check on Failures ❌
-      #        if: success()
-      #        shell: pwsh
-      #        run: |
+      # 构建前检查
+      - name: Check on Failures ❌
+        if: success()
+        shell: pwsh
+        run: |
+          $NOT_PASSED=0
+          echo "Build Version: v${env:BUILD_VERSION}`nCurrent Tag: ${env:GIT_TAG}`nLatest Tag: ${env:GIT_TAG_LATEST}`n"
+          if (!(${env:GIT_TAG} -match ${env:VERSION_REGEXP}) -or ${env:GIT_TAG} -eq '') {
+            $NOT_PASSED=1
+            echo "Cannot get the version information."
+          }
+
+          if ($NOT_PASSED -eq 0) {
+            $INTERNAL_VERSION_REGEXP='^(\d+\.\d+\.\d+)(\.\d+)?$'
+            $fileVersion=cat .\versioninfo.json | jq -r '.FixedFileInfo.FileVersion'
+            $fileVersion=(echo $fileVersion | jq -r '.Major, .Minor, .Patch, .Build') -join '.'
+            $fileVersion=[regex]::Match($fileVersion, $INTERNAL_VERSION_REGEXP)
+            if (!$fileVersion.success) {
+              $NOT_PASSED=-1
+            } else {
+              $fileVersion=$fileVersion.Groups[1].Value
+            }
+
+            if ($NOT_PASSED -eq 0) {
+              $productVersion=cat .\versioninfo.json | jq -r '.FixedFileInfo.ProductVersion'
+              $productVersion=(echo $productVersion | jq -r '.Major, .Minor, .Patch, .Build') -join '.'
+              $productVersion=[regex]::Match($productVersion, $INTERNAL_VERSION_REGEXP)
+              if (!$productVersion.success) {
+                $NOT_PASSED=-1
+              } else {
+                $productVersion=$productVersion.Groups[1].Value
+              }
+            }
+          }
+
+          if (($NOT_PASSED -eq 0) -and (($productVersion -ne $fileVersion) -or (${env:BUILD_VERSION} -ne $productVersion))) {
+            $NOT_PASSED=1
+            echo "The version information has some differences.`nPlease check `"versioninfo.json`""
+          }
+
+          if (($NOT_PASSED -eq 0) -and ((${env:GIT_TAG_LATEST} -ne '' -and ${env:GIT_TAG}.replace('-pre', '') -lt ${env:GIT_TAG_LATEST}.replace('-pre', '') -or
+            (${env:GIT_TAG}.replace('-pre', '') -eq ${env:GIT_TAG_LATEST}.replace('-pre', '') -and (${env:GIT_TAG}.contains('-pre') -or !${env:GIT_TAG_LATEST}.contains('-pre')))))) {
+              $NOT_PASSED=1
+              echo "A newer or the current version already exists."
+          }
+          if ($NOT_PASSED -ge 0) {
+            echo "Check the version information is not passed."
+            echo "This build has been aborted."
+            exit 1
+          }
 
       # 配置Golang环境
       - name: Setup Go Environment 📍
@@ -85,6 +130,8 @@ jobs:
         run: |
           go version
           go env
+          go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
+          go generate -x
           mkdir -p .\build
 
       # 运行Golang测试
@@ -117,8 +164,8 @@ jobs:
         run: |
           cd $env:BUILD_PATH
           mkdir -p .\publish
-          $BUILD_X64_FILENAME="Clash.Mini_${env:GIT_BRANCH}_${env:BUILD_VERSION}_x64.exe"
-          $BUILD_X86_FILENAME="Clash.Mini_${env:GIT_BRANCH}_${env:BUILD_VERSION}_x86.exe"
+          $BUILD_X64_FILENAME="Clash.Mini_${env:GIT_BRANCH}_v${env:BUILD_VERSION}_x64.exe"
+          $BUILD_X86_FILENAME="Clash.Mini_${env:GIT_BRANCH}_v${env:BUILD_VERSION}_x86.exe"
           echo "BUILD_X64_FILENAME=$BUILD_X64_FILENAME" >> $env:GITHUB_ENV
           echo "BUILD_X86_FILENAME=$BUILD_X86_FILENAME" >> $env:GITHUB_ENV
           cp .\Clash.Mini_*.exe .\publish\
